### ISSUE TITLE
Consider adding `cmkr` topic to the repo

### ISSUE THREAD

**Issue by mrexodia** [mike1k/perses#4]
Heya,

Would be nice if you could add the [cmkr topic](https://github.com/topics/cmkr) to the repository (and maybe a few others like x86, obfuscation, etc for better discoverability). I'm using it to make sure new releases stay compatible and to look for possible ways to improve.

Cheers,

Duncan

**Comment by mike1k** [comment]
Thanks, I forgot to add this. Done now.
