### ISSUE TITLE
this is literally garbage

### ISSUE THREAD

**Issue by ghost** [mike1k/perses#8]
dude the sdk makes the program crash, what the fuck, do you actual code ?

**Comment by Fabi** [comment]
> dude the sdk makes the program crash, what the fuck, do you actual code ?

I would say you are the issue

**Comment by invlpg** [comment]
> dude the sdk makes the program crash, what the fuck, do you actual code ?

The wicked plots against the righteous
and gnashes his teeth at him,
but the Lord laughs at the wicked,
for he sees that his day is coming.
